# @package _group_
name: muon

# Base Optimizer (AdamW) Parameters
learning_rate: 3e-4
min_learning_rate: 3e-5
weight_decay: 0.1
warmup_steps: 2000

# Muon-Specific Parameters
muon_learning_rate: 0.02
muon_momentum: 0.95
muon_nesterov: True
muon_ns_steps: 5
muon_weight_decay: 0.01
