def merge(
    raw_pretokens: dict[bytes, int],
    initial_vocab_bytes: dict[int, bytes],
    max_vocab_size: int,
) -> tuple[dict[int, bytes], list[tuple[bytes, bytes]]]: ...
def pretokenize_bytes(data: bytes, special_tokens: list[str]) -> dict[bytes, int]: ...
def pretokenize_file(path: str, special_tokens: list[str]) -> dict[bytes, int]: ...
def pretokenize(data: bytes, special_tokens: list[str]) -> dict[bytes, int]: ...
